'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { Hero } from '@/components/Hero';
import { UploadForm } from '@/components/UploadForm';
import { Toast } from '@/components/Toast';
import { ConfirmDialog } from '@/components/ConfirmDialog';
import { deleteDocument, ApiError, fetchDocumentDetail, fetchDocuments } from '@/lib/api';
import { getOptionalAccessToken } from '@/lib/auth';
import { DocumentDetail, DocumentSummary } from '@/lib/types';
import { useAuthStatus } from '@/lib/useAuthStatus';
export default function HomePage(){const [documents,setDocuments]=useState<DocumentSummary[]>([]);const [downloadableDocuments,setDownloadableDocuments]=useState<DocumentDetail[]>([]);const [error,setError]=useState('');const [toastMessage,setToastMessage]=useState('');const [deletingDocumentId,setDeletingDocumentId]=useState('');const [downloadedDocumentIds,setDownloadedDocumentIds]=useState<Record<string, boolean>>({});const {isAuthenticated,isLoading}=useAuthStatus();const detailCacheRef=useRef<Record<string,{detail?:DocumentDetail;docxAvailable:boolean;lastCheckedAt:number}>>({});
const loadDownloadableDocuments=useCallback(async(docs:DocumentSummary[])=>{const completed=docs.filter(d=>d.status==='completed').sort((a,b)=>b.id.localeCompare(a.id));const downloadable:DocumentDetail[]=[];const now=Date.now();for(const doc of completed){const cached=detailCacheRef.current[doc.id];if(cached?.docxAvailable&&cached.detail){downloadable.push(cached.detail);continue;}if(cached&&!cached.docxAvailable&&now-cached.lastCheckedAt<60000)continue;try{const detail=await fetchDocumentDetail(doc.id);detailCacheRef.current[doc.id]={detail,docxAvailable:detail.docx_available,lastCheckedAt:now};if(detail.docx_available)downloadable.push(detail);}catch{}}setDownloadableDocuments(downloadable);},[]);
const loadDocuments=useCallback(async()=>{if(!isAuthenticated){setDocuments([]);setDownloadableDocuments([]);detailCacheRef.current={};return;}try{const docs=await fetchDocuments();setDocuments(docs);await loadDownloadableDocuments(docs);setError('');}catch(err){setError(err instanceof Error?err.message:'Could not load conversions.');}},[isAuthenticated,loadDownloadableDocuments]);
useEffect(()=>{if(!isAuthenticated)return;void loadDocuments();const i=setInterval(()=>void loadDocuments(),15000);return()=>clearInterval(i)},[isAuthenticated,loadDocuments]);
useEffect(()=>{if(typeof window==='undefined')return;setDownloadedDocumentIds(downloadableDocuments.reduce<Record<string,boolean>>((a,d)=>{a[d.document_id]=window.sessionStorage.getItem(`auto-download-consumed:${d.document_id}`)==='1';return a;},{}))},[downloadableDocuments]);
useEffect(()=>{if(!toastMessage&&!error&&(!isLoading&&isAuthenticated))return;const t=window.setTimeout(()=>{setToastMessage('');setError('');},3500);return()=>window.clearTimeout(t)},[toastMessage,error,isLoading,isAuthenticated]);
const [pendingDeleteDocumentId,setPendingDeleteDocumentId]=useState('');const handleDeleteDocument=useCallback(async(id:string)=>{setDeletingDocumentId(id);try{const token=await getOptionalAccessToken();await deleteDocument(id,token);setDownloadableDocuments(c=>c.filter(i=>i.document_id!==id));setDocuments(c=>c.filter(i=>i.id!==id));window.sessionStorage.removeItem(`auto-download-consumed:${id}`);setToastMessage('Document deleted.');setPendingDeleteDocumentId('');}catch(err){let m='Delete failed. Please retry.';if(err instanceof ApiError&&err.status===422)m='Invalid document id.';else if(err instanceof ApiError&&err.status===404)m='Document not found or already deleted.';setError(m);}finally{setDeletingDocumentId('');}},[]);
return <><Hero /><section className='container page'><ConfirmDialog isOpen={Boolean(pendingDeleteDocumentId)} title='Delete document' description='Delete this document now? This cannot be undone.' confirmLabel='Delete' cancelLabel='Cancel' isBusy={Boolean(deletingDocumentId)} onCancel={()=>{if(!deletingDocumentId)setPendingDeleteDocumentId('');}} onConfirm={()=>{if(pendingDeleteDocumentId)void handleDeleteDocument(pendingDeleteDocumentId);}} /><Toast message={toastMessage||error||(!isAuthenticated&&!isLoading?'You must sign in to upload and convert files.':'')} tone={error||(!isAuthenticated&&!isLoading)?'error':'success'} onClose={()=>{setToastMessage('');setError('');}} /><div className='grid grid-2'><UploadForm onComplete={loadDocuments} isAuthenticated={isAuthenticated} /><div className='card'><h2 className='section-title'>Downloadable files</h2><div className='stack-sm'>{downloadableDocuments.length?downloadableDocuments.map(document=><div key={document.document_id} className='panel' style={{padding:'12px'}}><p className='small'><strong>File:</strong> {document.original_filename}</p><div className='actions-row'><a className='btn btn-secondary' href={`/document?documentId=${document.document_id}`}>View GPMB</a><a className='btn btn-primary' href={`/document?documentId=${document.document_id}&download=1`}>Download DOCX</a>{downloadedDocumentIds[document.document_id]?<button type='button' className='btn btn-danger' onClick={()=>setPendingDeleteDocumentId(document.document_id)} disabled={Boolean(deletingDocumentId)}>Delete</button>:null}</div></div>):<p className='small muted'>Your downloadable files will appear here after OCR processing finishes.</p>}</div></div></div></section></>}
