'use client';
import { useEffect, useState } from 'react';
import { Toast } from '@/components/Toast';
import { fetchDocumentDetail, initDocumentUpload, processDocument, uploadDocumentBinary } from '@/lib/api';
import { getOptionalAccessToken } from '@/lib/auth';
type UploadStage='idle'|'uploading'|'processing'|'completed'|'failed'; type FileJobState={fileName:string;stage:UploadStage;message:string};
export function UploadForm({ onComplete, isAuthenticated }: { onComplete?: () => Promise<void> | void; isAuthenticated: boolean }) {
const [files,setFiles]=useState<File[]>([]);const [translationFriendly,setTranslationFriendly]=useState(true);const [preserveLayout,setPreserveLayout]=useState(false);const [message,setMessage]=useState('');const [isBusy,setIsBusy]=useState(false);const [stage,setStage]=useState<UploadStage>('idle');const [fileStatuses,setFileStatuses]=useState<FileJobState[]>([]);
useEffect(()=>{if(!message)return;const t=setTimeout(()=>setMessage(''),3200);return()=>clearTimeout(t)},[message]);
async function wait(ms:number){await new Promise(r=>setTimeout(r,ms));}
async function pollUntilFinished(documentId:string,token:string|undefined,fileName:string){for(let i=0;i<120;i++){const d=await fetchDocumentDetail(documentId,token);const s=(d.document_status??d.job_status??'processing').toLowerCase();setFileStatuses(c=>c.map(it=>it.fileName===fileName?{...it,stage:s==='failed'?'failed':'processing',message:`Step: ${d.current_step??'queued'}`} :it));if(s==='completed'||d.docx_available){setFileStatuses(c=>c.map(it=>it.fileName===fileName?{...it,stage:'completed',message:'DOCX ready for download.'}:it));return;}if(s==='failed'||s==='expired'){setFileStatuses(c=>c.map(it=>it.fileName===fileName?{...it,stage:'failed',message:d.error_message||`Processing ${s}.`}:it));return;}await wait(2000);}}
async function handleUpload(){if(!files.length||!isAuthenticated)return;setIsBusy(true);setStage('uploading');setMessage('Uploading files...');try{const token=await getOptionalAccessToken();setFileStatuses(files.map(f=>({fileName:f.name,stage:'uploading',message:'Uploading...'})));for(const file of files){const init=await initDocumentUpload({filename:file.name,content_type:file.type||'application/pdf',size_bytes:file.size},token);await uploadDocumentBinary(init.upload_url,file,token);await processDocument(init.document_id,{engine_policy:'auto',translation_friendly:translationFriendly,preserve_layout:preserveLayout},token);await pollUntilFinished(init.document_id,token,file.name);}setStage('completed');setMessage('All files were submitted.');setFiles([]);await onComplete?.();}catch(e){setMessage(e instanceof Error?e.message:'Conversion failed.');setStage('failed');}finally{setIsBusy(false)}}
return <div className='card stack'><Toast message={message||(!isAuthenticated?'Please sign in before converting files.':'')} tone={stage==='failed'||!isAuthenticated?'error':stage==='completed'?'success':'info'} onClose={()=>setMessage('')} /><h2 className='section-title'>Upload PDF</h2><p className='small muted'>Select a PDF file to convert it into an editable DOCX document.</p><div className='dropzone'><input className='input' type='file' accept='application/pdf,image/jpeg,image/png,image/tiff,image/webp,image/bmp' onChange={(e)=>setFiles(Array.from(e.target.files??[]))}/></div><div className='stack-sm'><label className='check-row'><input type='checkbox' checked={translationFriendly} onChange={(e)=>setTranslationFriendly(e.target.checked)} disabled={isBusy}/>Translation friendly output</label><label className='check-row'><input type='checkbox' checked={preserveLayout} onChange={(e)=>setPreserveLayout(e.target.checked)} disabled={isBusy}/>Preserve original layout</label></div><div className='actions-row'><button className='btn btn-primary' onClick={handleUpload} disabled={!files.length||isBusy||!isAuthenticated}>{isBusy?'Working...':'Convert to DOCX'}</button></div>{isBusy?<div className='processing-indicator'><span className='spinner'/><span>{stage==='processing'?'Processing':'Uploading'}</span></div>:null}{fileStatuses.length?<ul className='small upload-status-list'>{fileStatuses.map(i=><li key={i.fileName}><strong>{i.fileName}:</strong> {i.message}</li>)}</ul>:null}</div>}
